app:
  name: ariskaAdi-online-shop
  port: 4000
  encryption:
    salt: 10
    jwt_secret: secretToken

db:
  host: localhost
  port: 5432
  name: online-shop
  user: postgres
  password: postgres
  connection_pool:
    max_idle_connection: 10
    max_open_connection: 30
    max_lifetime_connection: 60 #second
    max_idle_time_connection: 60 #second
